@echo off
set SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.0.155:30032/mydb
set SPRING_DATASOURCE_USERNAME=user
set SPRING_DATASOURCE_PASSWORD=password
set SPRING_KAFKA_BOOTSTRAP_SERVERS=192.168.0.155:30092
set SPRING_KAFKA_CONSUMER_GROUP_ID=candidate-service

echo Environment variables set:
echo SPRING_DATASOURCE_URL=%SPRING_DATASOURCE_URL%
echo SPRING_DATASOURCE_USERNAME=%SPRING_DATASOURCE_USERNAME%
echo SPRING_DATASOURCE_PASSWORD=%SPRING_DATASOURCE_PASSWORD%
echo SPRING_KAFKA_BOOTSTRAP_SERVERS=%SPRING_KAFKA_BOOTSTRAP_SERVERS%
echo SPRING_KAFKA_CONSUMER_GROUP_ID=%SPRING_KAFKA_CONSUMER_GROUP_ID% 