# PowerShell script to help set up Jenkins credentials

Write-Host "Please follow these steps to set up Jenkins credentials:"
Write-Host "`n1. Open Jenkins in your browser"
Write-Host "2. Go to 'Manage Jenkins'"
Write-Host "3. Click on 'Manage Credentials'"
Write-Host "4. Click on 'System' under 'Stores scoped to Jenkins'"
Write-Host "5. Click on 'Global credentials'"
Write-Host "6. Click 'Add Credentials'"
Write-Host "`nFor Docker credentials:"
Write-Host "- Kind: Username with password"
Write-Host "- Scope: Global"
Write-Host "- Username: techbu"
Write-Host "- Password: techbu@Stl2025"
Write-Host "- ID: docker-credentials"
Write-Host "- Description: Docker Hub credentials"
Write-Host "`nFor Kubernetes credentials:"
Write-Host "- Kind: Secret file"
Write-Host "- Scope: Global"
Write-Host "- File: Upload your kubeconfig file"
Write-Host "- ID: kubeconfig-jenkins"
Write-Host "- Description: Kubernetes Config File"
Write-Host "`nAfter adding these credentials, try running the pipeline again." 