apiVersion: v1
kind: Service
metadata:
  name: candidate-service
  namespace: hcm
spec:
  selector:
    app: candidate-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP 