apiVersion: v1
kind: ConfigMap
metadata:
  name: candidate-service-config
  namespace: hcm
  labels:
    app: candidate-service
    component: candidate
data:
  application.properties: |
    # Application Configuration
    spring.application.name=candidate-microservice
    server.port=8080

    # OpenAPI Configuration
    springdoc.api-docs.path=/api-docs
    springdoc.swagger-ui.path=/swagger-ui.html
    springdoc.swagger-ui.operationsSorter=method
    springdoc.swagger-ui.tagsSorter=alpha
    springdoc.swagger-ui.tryItOutEnabled=true
    springdoc.swagger-ui.filter=true
    springdoc.swagger-ui.syntaxHighlight.activated=true
    springdoc.swagger-ui.syntaxHighlight.theme=monokai
    springdoc.default-produces-media-type=application/json
    springdoc.default-consumes-media-type=application/json
    springdoc.packagesToScan=tech.stl.hcm.candidate.controller

    # Kafka Configuration
    spring.kafka.bootstrap-servers=192.168.0.155:30092
    spring.kafka.consumer.group-id=hcm-candidate-service-group
    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
    spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
    spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
    spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
    spring.kafka.consumer.properties.spring.json.trusted.packages=tech.stl.hcm.candidate.dto
    
    # Kafka Retry and Error Handling
    spring.kafka.producer.retries=3
    spring.kafka.producer.properties.retry.backoff.ms=1000
    spring.kafka.consumer.auto-offset-reset=earliest
    spring.kafka.consumer.properties.max.poll.interval.ms=300000
    spring.kafka.consumer.properties.session.timeout.ms=60000
    
    # Kafka Security and Connection Settings
    spring.kafka.properties.security.protocol=PLAINTEXT
    spring.kafka.properties.client.id=candidate-service
    spring.kafka.producer.acks=all
    spring.kafka.producer.properties.enable.idempotence=true
    spring.kafka.consumer.properties.isolation.level=read_committed

    # Kafka Topics
    kafka.topic.candidate-created=candidate-created
    kafka.topic.candidate-updated=candidate-updated
    kafka.topic.candidate-deleted=candidate-deleted

    # Actuator Configuration
    management.endpoints.web.exposure.include=health,metrics,prometheus,info
    management.endpoint.health.show-details=always 