apiVersion: v1
kind: ConfigMap
metadata:
  name: candidate-service-config
  namespace: hcm
  labels:
    app: candidate-service
    component: candidate
data:
  application.properties: |
    # Application Configuration
    spring.application.name=candidate-microservice
    server.port=8080

    # Kafka Configuration
    spring.kafka.bootstrap-servers=192.168.0.155:30092
    spring.kafka.consumer.group-id=hcm-candidate-service-group
    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
    spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
    spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
    spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
    spring.kafka.consumer.properties.spring.json.trusted.packages=tech.stl.hcm.candidate.dto

    # Kafka Topics
    kafka.topic.candidate-created=candidate-created
    kafka.topic.candidate-updated=candidate-updated
    kafka.topic.candidate-deleted=candidate-deleted

    # Actuator Configuration
    management.endpoints.web.exposure.include=health,metrics,prometheus,info
    management.endpoint.health.show-details=always 