apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hcm

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secrets.yaml

commonLabels:
  app: candidate-service
  component: candidate

images:
  - name: techbu/hcm
    newTag: latest 