apiVersion: v1
kind: Service
metadata:
  name: candidate-service
  namespace: hcm
  labels:
    app: candidate-service
    component: candidate
spec:
  selector:
    app: candidate-service
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP 