apiVersion: v1
kind: Service
metadata:
  name: candidate-service
  namespace: hcm
  labels:
    app: candidate-service
    component: candidate
spec:
  type: NodePort
  selector:
    app: candidate-service
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30011
    protocol: TCP
    name: http 